[tool.poetry]
name = "omnibenchmark"
version = "0.1.0"
description = "An tool for automated scientific benchmarking"
authors = ["almutlue <almut.lue@gmail.com>", "Izaskun Mallona <izaskun.mallona@gmail.com>"]
readme = "README.md"
packages = [{include = "omni"}]
homepage = "https://github.com/omnibenchmark/omni-py"
repository = "https://github.com/omnibenchmark/omni-py"
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python"
]

[tool.poetry.dependencies]
python = "^3.12" # so snmk >8 is installable
setuptools="^72.1.0"
easybuild="^4.9.2"
easybuild-easyblocks="^4.9.2"
omni-schema = {git = "https://github.com/omnibenchmark/omni-schema.git", rev = "version/0.0.2"}
typer = {extras = ["all"], version = "^0.12.3"}
typing-extensions = "^4.11.0"
snakemake="^8.11.6"
snakedeploy="^0.10.0"
## io start ----------------
aiohttp = "^3.9.5"
async = "^0.6.2"
tqdm = "^4.66.4"
requests = "^2.31.0"
bs4 = "^0.0.2"
lxml = "^5.2.1"
python-dateutil = "^2.9.0.post0"
minio = "^7.2.7"
python-swiftclient = { version = "^4.5.0", optional = true}
boto3 = {version = "^1.34.102", optional = true}
pre-commit = "^3.7.1"
isort = "^5.13.2"
testcontainers = "^4.5.1"
## io end -----------------

pytest-cov = "^4.1.0"
pytest-split = "^0.9.0"
pytest-xdist = "^3.6.1"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.6.0"
black = "^23.12.0"

# removing these due from the group due to
# https://stackoverflow.com/questions/76118614/is-it-possible-to-install-poetry-groups-with-pip
# [tool.poetry.group.test.dependencies]
# pytest-cov = "^4.1.0"
# pytest-split = "^0.9.0"
# pytest-xdist = "^3.6.1"
# genbadge = {extras = ["coverage", "tests"], version = "^1.1.1"}

[tool.poetry.scripts]
ob = 'omni.cli.main:cli'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
