[tool.poetry]
name = "omni"
version = "0.1.0"
description = ""
authors = ["almutlue <almut.lue@gmail.com>"]
readme = "README.md"
packages = [{include = "omni"}]
homepage = "https://github.com/almutlue/omni-py"
repository = "https://github.com/almutlue/omni-py"
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python"
]

[tool.poetry.dependencies]
python = "^3.11"
typer = {extras = ["all"], version = "^0.12.3"}
typing-extensions = "^4.11.0"

aiohttp = "^3.9.5"
async = "^0.6.2"
tqdm = "^4.66.4"
requests = "^2.31.0"
bs4 = "^0.0.2"
lxml = "^5.2.1"
python-dateutil = "^2.9.0.post0"
minio = "^7.2.7"
python-swiftclient = { version = "^4.5.0", optional = true}
boto3 = {version = "^1.34.102", optional = true}
pre-commit = "^3.7.1"
isort = "^5.13.2"
testcontainers = "^4.5.1"


matplotlib = "3.8.0"
networkx = "^3.3"

omni-schema = {git = "https://github.com/omnibenchmark/omni-schema.git", rev = "version/0.0.2"}
snakemake = "^8.16.0"
[tool.poetry.group.dev.dependencies]
pre-commit = "^3.6.0"
black = "^23.12.0"
pytest-cov = "^4.1.0"


[tool.poetry.group.test.dependencies]
genbadge = {extras = ["coverage", "tests"], version = "^1.1.1"}
argparse = "^1.4.0"

[tool.poetry.scripts]
ob = 'omni.cli.main:cli'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
s3 = ["boto3"]
swift = ["python-swiftclient"]

[tool.isort]
profile = "black"
